# Generated by Django 3.0.8 on 2020-08-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200815_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last',
        ),
    ]
